# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3664db44aecb21676482a121cb99d3ccdae3d5c27d27e58683c0fa99c122294eb4f9518ca79a3992499315619556af9a062e7977f4bb317324ec1cbb07a41de

test:
  secret_key_base: 84a8c23a5a00335068115de811b6bd15609498fbe9357edc3df0efaeffbe4c0430bbad1913eaa2723d4d221067daf69f23e09a43b5c464a63bdf93d4e3803285

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
